### ISSUE TITLE
Flashing header during transition from issue to index

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1701]
https://youtu.be/RLi7RX2m3Xc

**Comment by rnystrom** [comment]
Hmmmmm my guess is that the view of the issues VC doesn’t have a background set? Something has a black background and it’s bleeding through.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Also I tried to report this through the app but "report a bug" was broken. I assumed it would be fixed imminently, but if it's still broken  I'll report it separately.

**Comment by rnystrom** [comment]
Already tracking, it’s from the org move

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Closing b/c it looks like this is fixed on the latest TF build? I didn't do anything... 🤷‍♀️

**Comment by gingerbeardman** [comment]
I'm still seeing it

![GitHawk Upload by gingerbeardman](https://i.imgur.com/zwcsp7h.jpg)

**Comment by rnystrom** [comment]
@gingerbeardman which version of iOS?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
11.3 (15E216)

It looks to me that the flashing is changing transparencyof whatever is behind the overlap of the header.

**Comment by gingerbeardman** [comment]
Reproduction: 
Whilst reading this comment in GitHawk swipe slowly from the left edge of the screen

**Comment by rnystrom** [comment]
Hmm ya doesn’t happen for me, gonna leave closed unless it resurfaced with more detail on what’s going on 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Strange, now it's not doing it for me in this issue. I'll keep an eye out

**Comment by gingerbeardman** [comment]
OK. Here are new steps to reproduce:

1. Start GitHawk fresh
**2. Tap a link that opens in a web view**
3. Swipe screen slowly from left edge
4. Notice the flashing

It does not happen unless a web view has been opened.

**Comment by BasThomas** [comment]
🤔 so the only blackish thing I can find in the view hierarchy is this `UILayoutContainerView` from the `UISplitViewController`.

<img width="1381" alt="screen shot 2018-04-10 at 23 33 07" src="https://user-images.githubusercontent.com/4190298/38584753-9295f0bc-3d17-11e8-9408-7d513f5f213c.png">

**Comment by gingerbeardman** [comment]
I think the "something black" is a red herring?

**Comment by BasThomas** [comment]
It might be 🤷‍♂️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya those are the CALayers storing text bitmaps.

Thanks for the repro steps @gingerbeardman! I’ll take a look when I have time.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
